"""PR label classifier — the single source of truth for the labelling strategy
(docs/pr-labels.md).

Titles in this repo are machine-generated by the swarm (`prove(<goal>): …`,
`tr(<goal>): …`, `affinity(<goal>): …`, `redteam<round>(<vector>): …`) or
conventional-commit shaped (`feat:`, `fix:`, `chore:`, `docs:`, with
`docs(vX.Y.Z):` reserved for release housekeeping). The classifier maps a
title to labels; the CI auto-labeler (.github/workflows/pr-labels.yml) and the
retro pass both call it, so the rules live in exactly one place.

Usage:  python3 -m tools.repo.pr_labels classify "<pr title>"   # one label per line
"""
from __future__ import annotations

import re
import sys

#: Label name → (colour, description). `gh label create` consumes this table.
LABELS: dict[str, tuple[str, str]] = {
    "swarm:translate": ("1d76db", "Agent translation/convergence PR (Phase-0/1 loop)"),
    "swarm:prove": ("0e8a16", "Agent proof PR (prove cycle)"),
    "swarm:decompose": ("5319e7", "Agent decomposition PR (ADR-009)"),
    "swarm:demote": ("e99695", "Agent affinity-demote PR (ADR-010)"),
    "red-team": ("b60205", "Adversarial gate-bypass attempt — expected to be blocked"),
    "docs": ("0075ca", "Documentation, ADRs, specs, proposals"),
    "metrics": ("c5def5", "Run-evidence records (docs/metrics)"),
    "release": ("ededed", "Version housekeeping and tag"),
    "feat": ("a2eeef", "New machinery"),
    "fix": ("d73a4a", "Bug fix"),
    "chore": ("fef2c0", "Housekeeping"),
}

_SWARM = {
    "tr": "swarm:translate",
    "converge": "swarm:translate",
    "prove": "swarm:prove",
    "decompose": "swarm:decompose",
    "affinity": "swarm:demote",
}
_SWARM_RE = re.compile(r"^(?P<kind>tr|converge|prove|decompose|affinity)\(")
_REDTEAM_RE = re.compile(r"^redteam\d*\(")
_RELEASE_RE = re.compile(r"^docs\(v\d")
_METRICS_RE = re.compile(r"\(run \d+\)|metrics|red-team round \d+", re.IGNORECASE)


def classify(title: str) -> list[str]:
    """Labels for a PR title, in stable order. Unknown shapes get none."""
    title = title.strip()
    m = _SWARM_RE.match(title)
    if m:
        return [_SWARM[m.group("kind")]]
    if _REDTEAM_RE.match(title):
        return ["red-team"]
    if _RELEASE_RE.match(title):
        return ["release"]
    if title.startswith("docs"):
        labels = ["docs"]
        if _METRICS_RE.search(title):
            labels.append("metrics")
        return labels
    for prefix in ("feat", "fix", "chore"):
        if title.startswith(prefix):
            return [prefix]
    return []


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if len(argv) == 2 and argv[0] == "classify":
        for label in classify(argv[1]):
            print(label)
        return 0
    if argv == ["labels"]:
        for name, (colour, desc) in LABELS.items():
            print(f"{name}\t{colour}\t{desc}")
        return 0
    print("usage: pr_labels.py classify '<title>' | labels", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
