"""PR label classifier — the single source of truth for the labelling strategy
(docs/pr-labels.md).

Titles in this repo are machine-generated by the swarm (`prove(<goal>): …`,
`tr(<goal>): …`, `affinity(<goal>): …`, `unblock(<goal>): …`,
`redteam<round>(<vector>): …`) or
conventional-commit shaped (`feat:`, `fix:`, `chore:`, `docs:`, with
`docs(vX.Y.Z):` reserved for release housekeeping). The classifier maps a
title to labels; the CI auto-labeler (.github/workflows/pr-labels.yml) and the
retro pass both call it, so the rules live in exactly one place.

Usage:
  python3 -m tools.repo.pr_labels classify "<pr title>"   # one label per line
  python3 -m tools.repo.pr_labels enforce  "<pr title>"   # exit 1 if nonconforming (ADR-026)
"""
from __future__ import annotations

import re
import sys

#: Label name → (colour, description). `gh label create` consumes this table.
LABELS: dict[str, tuple[str, str]] = {
    "swarm:translate": ("1d76db", "Agent translation/convergence PR (Phase-0/1 loop)"),
    "swarm:prove": ("0e8a16", "Agent proof PR (prove cycle)"),
    "swarm:decompose": ("5319e7", "Agent decomposition PR (ADR-009)"),
    "swarm:unblock": ("fbca04", "Parent goal re-opened after its sub-lemmas were proved (ADR-009)"),
    "swarm:demote": ("e99695", "Agent affinity-demote PR (ADR-010)"),
    "red-team": ("b60205", "Adversarial gate-bypass attempt — expected to be blocked"),
    "docs": ("0075ca", "Documentation, ADRs, specs, proposals"),
    "metrics": ("c5def5", "Run-evidence records (docs/metrics)"),
    "release": ("ededed", "Version housekeeping and tag"),
    "feat": ("a2eeef", "New machinery"),
    "fix": ("d73a4a", "Bug fix"),
    "chore": ("fef2c0", "Housekeeping"),
    "ci": ("bfdadc", "CI/CD and automation"),
    "test": ("bfdadc", "Tests"),
    "refactor": ("d4c5f9", "Refactor (no behaviour change)"),
    "perf": ("d4c5f9", "Performance"),
    "build": ("d4c5f9", "Build system / dependencies"),
}

_SWARM = {
    "tr": "swarm:translate",
    "converge": "swarm:translate",
    "prove": "swarm:prove",
    "decompose": "swarm:decompose",
    "unblock": "swarm:unblock",
    "affinity": "swarm:demote",
}
#: Swarm / red-team / release shapes all carry a `(<scope>):` — require the
#: closing `):` so a malformed `prove(goal)` (no colon) is rejected by the gate,
#: matching the documented `prove(<goal>): …` contract (ADR-026). `unblock(<goal>):`
#: re-opens a `blocked` parent once its sub-lemmas are proved (ADR-009).
_SWARM_RE = re.compile(r"^(?P<kind>tr|converge|prove|decompose|unblock|affinity)\([^()]*\):")
_REDTEAM_RE = re.compile(r"^redteam\d*\([^()]*\):")
_RELEASE_RE = re.compile(r"^docs\(v[\d.]+\):")
_METRICS_RE = re.compile(r"\(run \d+\)|metrics|red-team round \d+", re.IGNORECASE)
#: Conventional-Commits prefix with optional scope and breaking-change `!`,
#: requiring the `:` so a prose title ("fixed the thing") is NOT mistaken for a
#: typed change. Covers the full standard set so machinery PRs (ci/test/…) are
#: first-class, not rejected by the convention gate (ADR-026).
_CONVENTIONAL_RE = re.compile(
    r"^(?P<type>build|chore|ci|docs|feat|fix|perf|refactor|test)(?:\([^)]*\))?!?:"
)


def classify(title: str) -> list[str]:
    """Labels for a PR title, in stable order. Unknown shapes get none."""
    title = title.strip()
    m = _SWARM_RE.match(title)
    if m:
        return [_SWARM[m.group("kind")]]
    if _REDTEAM_RE.match(title):
        return ["red-team"]
    if _RELEASE_RE.match(title):
        return ["release"]
    c = _CONVENTIONAL_RE.match(title)
    if c:
        kind = c.group("type")
        if kind == "docs":
            labels = ["docs"]
            if _METRICS_RE.search(title):
                labels.append("metrics")
            return labels
        return [kind]
    return []


def is_conforming(title: str) -> bool:
    """True iff the title matches a known shape (swarm, red-team, release, or a
    Conventional-Commits type). The CI gate (.github/workflows/pr-conventions.yml,
    ADR-026) requires this — a nonconforming title fails the PR. The contract is
    title discipline: fix the title, not the classifier."""
    return bool(classify(title))


#: Human-readable catalogue of accepted shapes, shown when the gate rejects.
VALID_SHAPES = (
    "Conventional Commits (scope optional): "
    "feat: / fix: / docs: / chore: / ci: / test: / refactor: / perf: / build: ;  "
    "swarm: prove(<goal>): [theorem proved] / decompose(<goal>): & affinity(<goal>): "
    "[theorem not proved — split / demoted] / unblock(<goal>): [parent re-opened, "
    "subs proved] / tr(<goal>): / converge(<goal>): ;  "
    "red-team: redteam<n>(<vector>): ;  release: docs(vX.Y.Z):"
)


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if len(argv) == 2 and argv[0] == "classify":
        for label in classify(argv[1]):
            print(label)
        return 0
    if argv == ["labels"]:
        for name, (colour, desc) in LABELS.items():
            print(f"{name}\t{colour}\t{desc}")
        return 0
    if len(argv) == 2 and argv[0] == "enforce":
        if is_conforming(argv[1]):
            return 0
        print(
            f"PR title does not match any allowed shape:\n  {argv[1].strip()!r}\n\n"
            f"Use one of — {VALID_SHAPES}\n\n"
            "See docs/pr-labels.md and ADR-026. One logical change per PR; "
            "do not mix a proof with harness/tooling changes.",
            file=sys.stderr,
        )
        return 1
    print("usage: pr_labels.py classify '<title>' | enforce '<title>' | labels", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
