name = "unsorryArchive0026"
version = "0.1.0"
keywords = ["math", "archive", "unsorry"]
defaultTargets = ["UnsorryArchive0026"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[lean_lib]]
name = "UnsorryArchive0026"
srcDir = "library"
globs = ["Unsorry.+"]
