"""Generate `docs/targets.md` — the human-facing worklist of backlog targets
(ADR-012). One row per prove goal: status, difficulty, source, reference.

Provenance (source / reference / absence) lives in `backlog/<id>.md` as light
`- **Field:** value` lines (Gate B does not validate the backlog markdown, so no
schema churn); status/difficulty come from the goal record, and the proved
marker from `library/index`. Deterministic — regenerate whenever goals change.

Usage:  python3 -m tools.sourcing.targets_board [<repo-root>] > docs/targets.md
        python3 -m tools.sourcing.targets_board --check [<repo-root>]   # CI drift check
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

_FIELD_RE = re.compile(r"^-\s*\*\*(?P<key>[A-Za-z ]+):\*\*\s*(?P<val>.+?)\s*$", re.MULTILINE)
_STATUS_RE = re.compile(r"status≜(\w+)")
_PHASE_RE = re.compile(r"phase≜(\w+)")
_DIFF_RE = re.compile(r"difficulty≜(\d+)")
_GOAL_RE = re.compile(r"goal≜([A-Za-z0-9][A-Za-z0-9-]*)")


def _proved(root: Path) -> set[str]:
    proved: set[str] = set()
    indices = [root / "library" / "index"]
    packages = root / "packages"
    if packages.is_dir():
        indices.extend(sorted(packages.glob("unsorry-archive-*/library/index")))
    for index in indices:
        if index.is_dir():
            for entry in index.glob("*.aisp"):
                m = _GOAL_RE.search(entry.read_text(encoding="utf-8"))
                if m:
                    proved.add(m.group(1))
    return proved


def _backlog_fields(root: Path, goal: str) -> dict[str, str]:
    md = root / "backlog" / f"{goal}.md"
    if not md.is_file():
        return {}
    text = md.read_text(encoding="utf-8")
    fields = {m.group("key").strip().lower(): m.group("val").strip()
              for m in _FIELD_RE.finditer(text)}
    # title: first non-empty non-heading line
    for line in text.splitlines():
        s = line.strip()
        if s and not s.startswith("#") and not s.startswith("-"):
            fields.setdefault("title", s)
            break
    return fields


def rows(root: Path) -> list[dict]:
    proved = _proved(root)
    out: list[dict] = []
    goals_dir = root / "goals"
    if not goals_dir.is_dir():
        return out
    for path in sorted(goals_dir.glob("*.aisp")):
        text = path.read_text(encoding="utf-8")
        if (_PHASE_RE.search(text) or [None, ""])[1] != "prove":
            continue
        goal = path.stem
        status = "proved" if goal in proved else (_STATUS_RE.search(text) or [None, "open"])[1]
        diff = (_DIFF_RE.search(text) or [None, ""])[1]
        fields = _backlog_fields(root, goal)
        out.append({
            "id": goal,
            "title": fields.get("title", goal),
            "status": status,
            "difficulty": diff,
            "source": fields.get("source", "—"),
            "reference": fields.get("reference", "—"),
            "absence": fields.get("absence", "—"),
            "upstream": _upstream_status(root, goal),
        })
    return out


_UPSTREAM_STATUS_RE = re.compile(r"^Status:\s*(\S+)", re.MULTILINE)


def _upstream_status(root: Path, goal: str) -> str:
    """The packet's Status line (ADR-020), '—' when no packet exists. The
    sponsor advances it by editing the packet (candidate → packet-ready →
    in-discussion → pr-open → merged | declined)."""
    packet = root / "docs" / "upstream" / f"{goal}.md"
    if not packet.is_file():
        return "—"
    m = _UPSTREAM_STATUS_RE.search(packet.read_text(encoding="utf-8"))
    return m.group(1) if m else "packeted"


_ORDER = {"open": 0, "blocked": 1, "flagged": 2, "translated": 3, "proved": 4}


def render(root: Path) -> str:
    data = rows(root)
    n_open = sum(1 for r in data if r["status"] == "open")
    n_proved = sum(1 for r in data if r["status"] == "proved")
    lines = [
        "# Targets",
        "",
        "<!-- generated by tools/sourcing/targets_board.py — do not edit by hand -->",
        "",
        "The unsorry worklist: theorems that are **already proven but not yet in mathlib**, "
        "vetted for absence and stated in Lean, waiting for an agent or a human to prove them. "
        "Claim one, open a PR, let the gates decide (see "
        "[Running an agent](../README.md#running-an-agent) and [ADR-012](adrs/ADR-012-Backlog-Sourcing.md)).",
        "",
        f"**{n_open} open · {n_proved} proved · {len(data)} total prove-goals.**",
        "",
        "| Goal | Status | Diff | Upstream | Source | Reference |",
        "|------|--------|:----:|----------|--------|-----------|",
    ]
    for r in sorted(data, key=lambda r: (_ORDER.get(r["status"], 9), r["id"])):
        title = r["title"].replace("|", "\\|")
        ref = r["reference"].replace("|", "\\|")
        src = r["source"].replace("|", "\\|")
        up = r["upstream"]
        if up != "—":
            up = f"[{up}](upstream/{r['id']}.md)"
        lines.append(
            f"| `{r['id']}` — {title} | {r['status']} | {r['difficulty'] or '—'} | {up} | {src} | {ref} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    check = "--check" in argv
    rest = [a for a in argv if a != "--check"]
    root = Path(rest[0]) if rest else Path.cwd()
    content = render(root)
    target = root / "docs" / "targets.md"
    if check:
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current != content:
            print("docs/targets.md is stale — regenerate with "
                  "`python3 -m tools.sourcing.targets_board > docs/targets.md`",
                  file=sys.stderr)
            return 1
        return 0
    sys.stdout.write(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
